### ISSUE TITLE
Unhandled Exception - Wheres the fav.csv?!

### ISSUE THREAD

**Issue by ItzBlackStar** [MyShiLingStar/ACNHPoker#19]
I can create an empty csv, then it asks where the log.csv is, create an empty csv of that and it runs fine, until it doesn't.

For the new people coming into this, how do we fix this?

**Comment by MyShiLingStar** [comment]
Those missing files are auto-generated when the program starts.

You might have placed the program under a folder where it can not create additional files.
Try moving it to the desktop or other working directory where it can create files.

**Comment by ItzBlackStar** [comment]
it doesn't, ill try restarting PC and try on another computer.

**Comment by ItzBlackStar** [comment]
nope, its the same on both. weather I click yes or no to downloading the images it crashes and tells me I need fav.csv.

**Comment by TheSmilez** [comment]
What Shiling means is that it automatically generates a .cvs file upon unzipping the file.

Delete your old files, download the latest release again, unzip the release file into your desktop or downloads folder, start up ACNHPoker.exe. Do not move anything, don’t create any files, don’t add any files to the directory. Run the exe, download images, don’t touch it until the download window goes away.

**Comment by TheSmilez** [comment]
Folder structure should look like this after extracting/unzipping:

`desktop\Release`
or
`yourFolder\Release`

Keep **_everything_** related to ACNH Poker in that `Release` folder.

**Comment by MyShiLingStar** [comment]
![Image](https://user-images.githubusercontent.com/816502/141414051-59dcaba1-c0ca-4831-aa7a-45a1893dc6a8.GIF)

Those files are created automatically when you run the program. 
"fav.csv" is created when the program starts. 
"log.csv" is created when the program logs something. Like when the program closes.
And same with other files needed for the program to run.

If for some reason the program can't create those files, it will throw an exception.
Please make sure you have placed the program in a proper working location so that files can be created. 
Please also check your antivirus software. It might have blocked the file creation because of a new unfamiliar program.

**Comment by ItzBlackStar** [comment]
@MyShiLingStar <3 my antivirus was blocking it. ty ty!
